[build]
  # Since your frontend is in the root, not in /src
  base = "."
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://your-backend-url.onrender.com/api"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Preview deploy settings
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"